name: Build C Lib
on:
  push:
    branches:
      - '**'

jobs:
  build-lib:
    strategy:
      matrix:
        # macos-12 for Intel Mac, macos-14 for Apple Chips Mac
        os: [ ubuntu-20.04, windows-2019, macos-12, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew generateGrammarFilesEnhanced
      - run: |
          pushd build/generated
          cmake CMakeLists.txt
          make
        shell: bash # let Windows use bash
      - uses: actions/upload-artifact@v3
        with:
          name: lib-${{ runner.os }}-${{ runner.arch }}
          path: |
            build/generated/lib*
            build/generated/*.dll
